apiVersion: v1
kind: Service
metadata:
  name: hivebox
  labels:
    app: hivebox
spec:
  type: ClusterIP
  selector:
    app: hivebox
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
